//! Maestro simulation result parsing.
//!
//! Parses Cadence Maestro "Detail" CSV exports generated by `maeExportOutputView`.
//! This is analogous to virtuoso-bridge-lite's `maestro/reader/runs.py` implementation.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Maestro simulation result structure (analogous to virtuoso-bridge-lite's runs.py output).
#[derive(Debug, Serialize, Deserialize, Default)]
#[allow(dead_code)]
pub struct MaestroResult {
    /// History name (e.g., "Interactive.7")
    pub history: String,
    /// List of test names
    pub tests: Vec<String>,
    /// Per-point results
    pub points: Vec<MaestroPoint>,
    /// Overall spec status ("passed" | "failed" | None)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overall_spec: Option<String>,
    /// Overall yield info
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overall_yield: Option<String>,
    /// Raw CSV text (optional, for debugging)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_csv: Option<String>,
}

/// Individual sweep point result.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub struct MaestroPoint {
    /// 1-indexed point number
    pub point: usize,
    /// Design variables at this point (e.g., VDD=0.9)
    pub parameters: HashMap<String, String>,
    /// Output values at this point
    pub outputs: HashMap<String, MaestroOutput>,
}

/// Individual output value from Maestro simulation.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub struct MaestroOutput {
    /// Numeric value as string (preserves precision)
    pub value: String,
    /// Spec limit (e.g., "< 20p")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spec: Option<String>,
    /// Weight for optimization
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weight: Option<String>,
    /// Pass/fail status
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pass_fail: Option<String>,
}

impl MaestroResult {
    /// Parse a Maestro "Detail" CSV export.
    ///
    /// The CSV format from `maeExportOutputView` is:
    /// ```text
    /// ,,Parameter,Nominal,,,
    /// Point,Test,Output,Nominal,Spec,Weight,Pass/Fail
    /// Parameters: VDD=0.9,...
    /// 1,ac_test,Gain_dB,21.63,,,
    /// 1,ac_test,Phase_deg,-135,,,,passed
    /// Parameters: VDD=1.1,...
    /// 2,ac_test,Gain_dB,22.81,,,
    /// ```
    ///
    /// Returns empty result on parse failure.
    #[allow(dead_code)]
    pub fn parse_csv(csv_content: &str, history: &str) -> Self {
        let mut result = Self {
            history: history.to_string(),
            tests: Vec::new(),
            points: Vec::new(),
            overall_spec: None,
            overall_yield: None,
            raw_csv: None,
        };

        let mut current_point: Option<usize> = None;
        let mut current_params: HashMap<String, String> = HashMap::new();
        let mut current_outputs: HashMap<String, MaestroOutput> = HashMap::new();
        let mut all_tests: std::collections::HashSet<String> = std::collections::HashSet::new();

        for line in csv_content.lines() {
            // Trim whitespace
            let line = line.trim();
            if line.is_empty() {
                continue;
            }

            // Clean up CSV artifacts: trailing 'n' (newline in CSV cell)
            let clean_line = line.trim_end_matches('n');

            // Check if this is a Parameters line
            // Format: "Parameters: VDD=0.9, VIN=1.0, ..."
            // Handle both "Parameters:" and "Parameters:" prefix
            let params_str = if clean_line.starts_with("Parameters:") {
                Some(clean_line.strip_prefix("Parameters:").unwrap().trim())
            } else if clean_line.starts_with("\"Parameters:") {
                // Handle quoted version: "Parameters: VDD=0.9"
                clean_line
                    .trim_matches('"')
                    .strip_prefix("Parameters:")
                    .map(|s| s.trim())
            } else {
                None
            };

            if let Some(params) = params_str {
                // Save previous point if exists
                if let Some(pt) = current_point.take() {
                    if !current_outputs.is_empty() || !current_params.is_empty() {
                        result.points.push(MaestroPoint {
                            point: pt,
                            parameters: std::mem::take(&mut current_params),
                            outputs: std::mem::take(&mut current_outputs),
                        });
                    }
                }
                // Parse parameters: "VDD=0.9, VIN=1.0"
                for param in params.split(',') {
                    let param = param.trim();
                    if let Some((key, val)) = param.split_once('=') {
                        let key = key.trim();
                        let val = val.trim();
                        if !key.is_empty() && !val.is_empty() {
                            current_params.insert(key.to_string(), val.to_string());
                        }
                    }
                }
                // NOTE: Don't continue here - there might be data on the same line or next line
                // Actually, in Maestro CSV, Parameters and data are on separate lines
                continue;
            }

            // Skip header/comment lines
            // Header format: ",,Parameter,Nominal,,," or "Point,Test,Output,..."
            if line.starts_with(',')
                || line.starts_with("Point,")
                || line.starts_with("\"\"\"")
                || line.starts_with('#')
            {
                continue;
            }

            // Parse data line: "1, ac_test, Gain_dB, 21.63, < 20p, 1, passed"
            let parts: Vec<&str> = line.split(',').collect();
            if parts.len() >= 4 {
                // First column is point number
                if let Ok(pt) = parts[0].trim().parse::<usize>() {
                    // Check if point changed (first point doesn't count as "changed")
                    let point_changed = current_point.map(|p| p != pt).unwrap_or(false);

                    if point_changed {
                        // Save previous point
                        if let Some(prev_pt) = current_point.take() {
                            if !current_outputs.is_empty() || !current_params.is_empty() {
                                result.points.push(MaestroPoint {
                                    point: prev_pt,
                                    parameters: std::mem::take(&mut current_params),
                                    outputs: std::mem::take(&mut current_outputs),
                                });
                            }
                        }
                        // Clear state for new point (params may be set by new Parameters line)
                        current_params.clear();
                        current_outputs.clear();
                    }

                    current_point = Some(pt);

                    // Parse output entry
                    let test_name = parts[1].trim().to_string();
                    let output_name = parts[2].trim().to_string();
                    let value = parts
                        .get(3)
                        .map(|s| s.trim().to_string())
                        .unwrap_or_default();
                    let spec = parts.get(4).and_then(|s| {
                        let s = s.trim();
                        if s.is_empty() {
                            None
                        } else {
                            Some(s.to_string())
                        }
                    });
                    let weight = parts.get(5).and_then(|s| {
                        let s = s.trim();
                        if s.is_empty() {
                            None
                        } else {
                            Some(s.to_string())
                        }
                    });
                    let pass_fail = parts.get(6).and_then(|s| {
                        let s = s.trim();
                        if s.is_empty() {
                            None
                        } else {
                            Some(s.to_string())
                        }
                    });

                    all_tests.insert(test_name.clone());

                    current_outputs.insert(
                        output_name.clone(),
                        MaestroOutput {
                            value,
                            spec,
                            weight,
                            pass_fail: pass_fail.clone(),
                        },
                    );

                    // Track overall spec status from first test
                    if result.overall_spec.is_none() {
                        result.overall_spec = pass_fail;
                    }
                }
            }
        }

        // Save last point
        if let Some(pt) = current_point {
            if !current_outputs.is_empty() || !current_params.is_empty() {
                result.points.push(MaestroPoint {
                    point: pt,
                    parameters: current_params,
                    outputs: current_outputs,
                });
            }
        }

        result.tests = all_tests.into_iter().collect();
        result.tests.sort();
        result
    }

    /// Get scalar value for a specific output at a specific point.
    #[allow(dead_code)]
    pub fn get_scalar(&self, point: usize, output: &str) -> Option<f64> {
        self.points
            .iter()
            .find(|p| p.point == point)
            .and_then(|p| p.outputs.get(output))
            .and_then(|o| o.value.parse().ok())
    }

    /// Check if all outputs pass their specs.
    #[allow(dead_code)]
    pub fn all_pass(&self) -> bool {
        self.points.iter().all(|p| {
            p.outputs
                .values()
                .all(|o| o.pass_fail.as_ref().map(|s| s == "passed").unwrap_or(true))
        })
    }

    /// Get the number of sweep points.
    #[allow(dead_code)]
    pub fn num_points(&self) -> usize {
        self.points.len()
    }

    /// Get a summary string for display.
    #[allow(dead_code)]
    pub fn summary(&self) -> String {
        let pass_count = self
            .points
            .iter()
            .filter(|p| {
                p.outputs
                    .values()
                    .all(|o| o.pass_fail.as_ref().map(|s| s == "passed").unwrap_or(true))
            })
            .count();

        format!(
            "history={} tests={} points={} passed={}/{}",
            self.history,
            self.tests.join(","),
            self.points.len(),
            pass_count,
            self.points.len()
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_single_point() {
        // CSV format with Parameters line followed by data
        let csv = "Parameters: VDD=0.9\n1,ac_test,Gain_dB,21.63,,,passed\n1,ac_test,Phase_deg,-135,,,passed";
        let result = MaestroResult::parse_csv(csv, "Interactive.1");

        assert_eq!(result.history, "Interactive.1");
        assert_eq!(result.tests, vec!["ac_test"]);
        assert_eq!(result.points.len(), 1);
        assert_eq!(result.points[0].point, 1);
        assert_eq!(
            result.points[0].parameters.get("VDD"),
            Some(&"0.9".to_string())
        );
        assert_eq!(
            result.points[0].outputs.get("Gain_dB").unwrap().value,
            "21.63"
        );
        assert_eq!(
            result.points[0]
                .outputs
                .get("Phase_deg")
                .unwrap()
                .pass_fail
                .as_deref(),
            Some("passed")
        );
        assert!(result.all_pass());
    }

    #[test]
    fn test_parse_multi_point() {
        let csv = "Parameters: VDD=0.9\n1,ac_test,Gain_dB,21.63,,,passed\nParameters: VDD=1.1\n2,ac_test,Gain_dB,22.81,,,passed";
        let result = MaestroResult::parse_csv(csv, "Interactive.7");

        assert_eq!(result.points.len(), 2);
        assert_eq!(result.points[0].point, 1);
        assert_eq!(result.points[1].point, 2);
        assert_eq!(
            result.points[0].parameters.get("VDD"),
            Some(&"0.9".to_string())
        );
        assert_eq!(
            result.points[1].parameters.get("VDD"),
            Some(&"1.1".to_string())
        );
    }

    #[test]
    fn test_parse_with_specs() {
        let csv =
            "1,ac_test,Gain_dB,21.63,< 20dB,1,passed\n1,ac_test,Bandwidth_Hz,1.2G,> 100M,1,passed";
        let result = MaestroResult::parse_csv(csv, "Interactive.2");

        let gain = result.points[0].outputs.get("Gain_dB").unwrap();
        assert_eq!(gain.spec.as_deref(), Some("< 20dB"));
        assert_eq!(gain.weight.as_deref(), Some("1"));
    }

    #[test]
    fn test_parse_with_trailing_n() {
        // CSV with trailing 'n' on lines (Maestro CSV artifact)
        let csv = "Parameters: VDD=0.9n\n1,test,out,1.0,,,passedn";
        let result = MaestroResult::parse_csv(csv, "Test.1");

        assert_eq!(
            result.points[0].parameters.get("VDD"),
            Some(&"0.9".to_string())
        );
    }

    #[test]
    #[allow(clippy::approx_constant)]
    fn test_get_scalar() {
        let csv = "1,test,val,3.14159,,,\n2,test,val,2.71828,,,";
        let result = MaestroResult::parse_csv(csv, "Test.1");

        assert_eq!(result.get_scalar(1, "val"), Some(3.14159));
        assert_eq!(result.get_scalar(2, "val"), Some(2.71828));
        assert_eq!(result.get_scalar(3, "val"), None);
        assert_eq!(result.get_scalar(1, "nonexistent"), None);
    }

    #[test]
    fn test_summary() {
        let csv = "1,test,out,1.0,,,passed\n2,test,out,2.0,,,failed";
        let result = MaestroResult::parse_csv(csv, "Test.1");

        let summary = result.summary();
        assert!(summary.contains("Test.1"));
        assert!(summary.contains("passed=1/2"));
    }

    #[test]
    fn test_all_pass() {
        let pass = "1,t,g,1.0,,,passed\n2,t,g,2.0,,,passed";
        let fail = "1,t,g,1.0,,,passed\n2,t,g,2.0,,,failed";

        assert!(MaestroResult::parse_csv(pass, "T.1").all_pass());
        assert!(!MaestroResult::parse_csv(fail, "T.1").all_pass());
    }

    #[test]
    fn test_empty_csv() {
        let result = MaestroResult::parse_csv("", "Empty.1");
        assert!(result.points.is_empty());
        assert!(result.tests.is_empty());
    }
}
